# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1g -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4500m

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true
org.gradle.workers.max=6

android.useAndroidX=true
android.nonTransitiveRClass=true
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
android.r8.runAsDaemon=false

kotlin.code.style=official
